import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'CLIO Kit',
      items: [
        'clio-kit/mcp-servers',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/configuration',
        'deployment/hpc-cluster',
        'deployment/performance',
        'deployment/monitoring',
      ],
    },
    {
      type: 'category',
      label: 'SDK Reference',
      link: {type: 'doc', id: 'sdk/index'},
      items: [
        {
          type: 'category',
          label: 'Context Runtime',
          link: {type: 'doc', id: 'sdk/context-runtime/overview'},
          items: [{type: 'autogenerated', dirName: 'sdk/context-runtime'}],
        },
        {
          type: 'category',
          label: 'Context Transfer Engine',
          items: [{type: 'autogenerated', dirName: 'sdk/context-transfer-engine'}],
        },
        {
          type: 'category',
          label: 'Context Assimilation Engine',
          items: [{type: 'autogenerated', dirName: 'sdk/context-assimilation-engine'}],
        },
        {
          type: 'category',
          label: 'Context Transport Primitives',
          items: [{type: 'autogenerated', dirName: 'sdk/context-transport-primitives'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/python',
        'api/agents',
        'api/storage',
      ],
    },
    'faq',
    'tutorials',
  ],
};

export default sidebars;
